# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: illusi0n7
google_analytics: illusi0n7
title: illusi0n7

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: illusi0n7's blog

description: Stylish Jekyll Theme
author:
  name: Hyunjin Kim
  email: stargazer.y@gmail.com
  github: illusi0n7
#  twitter: 
 # pinterest: asd123
  #linkedin: 
  bio: Share my memory
  email_md5: 6e9e1a950c1bc5aaaa2ea1929591c871

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate